on:
  push:
    branches:
      - master

name: master-ci

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - name: Code checkout
        uses: actions/checkout@master
      
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          
      - name: Build
        run: mvn clean package
